#欢迎来到杰基尔！
#
#此配置文件用于影响整个博客值的设置。
#它需要设置一次，之后很少需要编辑。
#由于技术原因，当您使用
#“杰基会发球的”。如果更改此文件，请重新启动服务器进程。

#站点设置
标题: 徐代龙的技术专栏
简介: Android和PythonCoder
基尔: "" #站点的子路径，例如/blog
URL: "https://hanjinhong.github.io" #站点的基本主机名和协议

permalink: /：年份/：月/：日/：标题/

#其他链接
twitter用户名: #web前端
facebook用户名: #韩金红
GitHub_用户名:  hanjinhong
电子邮件: 3012138587@qq.com
微博用户名: 保密
LinkedIn用户名: 韩金红
Dribbble用户名:

描述页脚: 来自徐代龙的个人专栏！

#评论意见
#两种注释方式，只选择一种，并使用自己的短名称。
#两种评论插件，选一个就好了，使用自己的短名
多朔名称: #hygblog
Disqus_昵称: #韩金红

#统计分析统计代码
#百度统计id，将统计代码替换为自己的百度统计id，即
#hm.src=“/hm.baidu.com/hm.js？xxxxxxxxxxx”；
#xxxx字符串
百度同济id: 552a8d99c04e57a157ba015b317ce20
谷歌分析id: UA-72449510-4#谷歌分析追踪id

#生成设置
标价: 克拉姆顿

克拉姆顿:
  输入: GFM
  语法荧光笔: 碳素笔

#港
#港口：1234

#URL
类别dir: 类别/
标记dir: 标签/

#节选
节选分离器: "\n"

#分页
插件: [杰基尔-帕格特]
分页: 6
港: 4001
2018年GitHub.=‘class 3’>公司
